### ISSUE TITLE
Prevent calling SecuredElementInterface::isAllowed() when there is no token in token storage

### ISSUE THREAD

**Issue by chives** [fsi-open/admin-security-bundle#43]
[SecuredElementListener](https://github.com/fsi-open/admin-security-bundle/blob/master/EventListener/SecuredElementListener.php#L51) should not call SecuredElementInterface::isAllowed() when there is no token, because it finally throws exception [here](https://github.com/symfony/Security/blob/master/Core/Authorization/AuthorizationChecker.php#L57)

**Comment by szymach** [comment]
The class `SecuredElementListener` does no longer exist in the master branch, so I think this issue can be closed.

**Comment by chives** [comment]
`SecuredElementListener` -> `RemoveNotGrantedElementsListener`
