### ISSUE TITLE
SecuredElement access exception

### ISSUE THREAD

**Issue by JarekW** [fsi-open/admin-security-bundle#63]
When the user enters a element to which it don't have permission (because of `SecuredElementInterface`), `AccessDeniedException` or similar should be thrown instead of current `NotFoundHttpException`. 
There is no easy way to distinguish between those 2 situations currently

**Comment by szymach** [comment]
Well should it? I do not know if a user without access should even know about the existence of elements, that he does not have the access to.

**Comment by szymach** [comment]
Resolved by #83 - accessing the a restricted element in code will result in `AccessDeniedException`, while attempting to open the page for it will throw `NotFoundHttpException`.
