### ISSUE TITLE
Update project description

### ISSUE THREAD

**Issue by shakaran** [fsi-open/admin-security-bundle#96]
Currently: 

`"Purpose of this bundle is to provide simple authentication & authorization mechanisms for fsi/admin-bundle"`

It should say: 

`"Purpose of this bundle is to provide simple authentication & authorization mechanisms for fsi-open/admin-bundle"`

Notice the fsi-open in fsi-open/admin-bundle

**Comment by szymach** [comment]
You literally copy pasted the same description. I assume you meant

```
"Purpose of this bundle is to provide simple authentication & authorization mechanisms for fsi-open/admin-bundle"
```

:)

**Comment by shakaran** [comment]
@szymach Yes, sorry, Updated ;)

**Comment by szymach** [comment]
Alright, we will update the project description sometime on Monday. Thanks for bringing this to our attention :)

**Comment by Konad-FSi** [comment]
Nice work

**Comment by szymach** [comment]
@shakaran we have updated the project description. To clarify - `fsi/` is the namespace we have for our projects on Packagist and `fsi-open` is our organization's name on Github (`fsi` was already taken, unfortunatly), hence the different description. We have decided to simply provide the link to the repository to prevent confusion :) Cheers.

**Comment by shakaran** [comment]
@szymach thanks!
